apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x3jm3rzzx-nodejs 
  janus-idp.io/tekton: x3jm3rzzx-nodejs
  backstage.io/kubernetes-id: x3jm3rzzx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x3jm3rzzx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml